package main

import (
	"fmt"
	"os"
)

// Global variable for CI stamping.
var version = "unknown - unofficial & generated by unknown"

func main() {
	cfg, err := parseFlags()
	if err != nil {
		fmt.Fprintln(os.Stderr, err)
		os.Exit(1)
	}

	if err := cfg.Validate(); err != nil {
		fmt.Fprintln(os.Stderr, err)

		os.Exit(1)
	}

	if err := run(cfg); err != nil {
		fmt.Fprintln(os.Stderr, err)

		os.Exit(1)
	}
}
