// Command gogen provides cryptographic key generation and password hashing functionality.
//
// Usage:
//
//	# Generate a 32-byte key
//	gogen key
//
//	# Generate a 64-byte key
//	gogen key -l 64
//
//	# Hash a password with default cost (12)
//	gogen hash password
//
//	# Hash a password with custom cost
//	gogen hash -c 14 password
//
//	# Run password hashing benchmark
//	gogen hash -b password
package main

import (
	"fmt"
	"os"

	"github.com/idelchi/gogen/internal/parse"
	"github.com/idelchi/gogen/pkg/stdin"
)

// version indicates the build version, set during compilation.
var version = "unknown - unofficial & generated by unknown"

func main2() {
	if err := parse.Execute(version); err != nil {
		fmt.Fprintln(os.Stderr, err.Error())

		os.Exit(1)
	}
}

func main() {
	fmt.Printf("stdin.IsPiped()=%v\n", stdin.IsPiped())

	isMaybePiped, err := stdin.MaybePiped()
	fmt.Printf("stdin.MaybePiped()=%v, err=%v\n", isMaybePiped, err)

	fmt.Printf("MaybePipedTermUtil=%v\n", stdin.MaybePipedTermUtil())
}
