// Command gogen provides cryptographic key generation and password hashing functionality.
//
// Usage:
//
//	# Generate a 32-byte key
//	gogen key
//
//	# Generate a 64-byte key
//	gogen key -l 64
//
//	# Hash a password with default cost (12)
//	gogen hash password
//
//	# Hash a password with custom cost
//	gogen hash -c 14 password
//
//	# Run password hashing benchmark
//	gogen hash -b password
package main

import (
	"fmt"
	"os"

	"github.com/idelchi/gogen/internal/parse"
)

// version indicates the build version, set during compilation.
var version = "unknown - unofficial & generated by unknown"

func main() {
	if err := parse.Execute(version); err != nil {
		fmt.Fprintln(os.Stderr, err.Error())

		os.Exit(1)
	}
}
