package main

import (
	"os"

	"github.com/idelchi/gocry/internal/printer"
)

var version = "unknown - unofficial & generated by unknown"

func main() {
	root := flags()

	if err := root.Execute(); err != nil {
		printer.Stderrln(err.Error())

		os.Exit(1)
	}
}
